import { Auto, Factors, IinitialFormCreate } from "../Interfaces/Interfaces";

export const mockData: Auto[] = [
    {
        id: 1,
        identificacion: 'Cliente 1',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 2,
        identificacion: 'Cliente 2',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 3,
        identificacion: 'Cliente 3',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 4,
        identificacion: 'Cliente 4',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 5,
        identificacion: 'Cliente 5',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 6,
        identificacion: 'Cliente 6',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 7,
        identificacion: 'Cliente 7',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 8,
        identificacion: 'Cliente 8',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 9,
        identificacion: 'Cliente 9',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 10,
        identificacion: 'Cliente 10',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 11,
        identificacion: 'Cliente 11',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 12,
        identificacion: 'Cliente 12',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 13,
        identificacion: 'Cliente 13',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 14,
        identificacion: 'Cliente 14',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 15,
        identificacion: 'Cliente 15',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 16,
        identificacion: 'Cliente 16',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 17,
        identificacion: 'Cliente 17',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 18,
        identificacion: 'Cliente 18',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 19,
        identificacion: 'Cliente 19',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 20,
        identificacion: 'Cliente 20',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },
    {
        id: 21,
        identificacion: 'Cliente 21',
        modelo: '2023',
        factoresCompra: 'Recomendaciones',
        calificacionPrueba: 4,
        calificacionSatisfaccion: 5,
    },

    // Agrega más autos según sea necesario
];

export const mockFactors: Factors[] = [
    { value: '', label: 'Seleccione una opción' },
    { value: 'Reputación de la Marca', label: 'Reputación de la Marca' },
    { value: 'Opciones de Financiamiento', label: 'Opciones de Financiamiento' },
    { value: 'Desempeño al Manejarlo', label: 'Desempeño al Manejarlo' },
    { value: 'Recomendaciones', label: 'Recomendaciones' },
    { value: 'Otros', label: 'Otros' },
]

export const initialFormCreate: IinitialFormCreate = {
    identificacion: '',
    modelo: '2023',
    factoresCompra: '',
    calificacionPrueba: 1,
    calificacionSatisfaccion: 1,
}