import { Auto, Factors, IinitialFormCreate, IinitialFormEdit } from "../Interfaces/Interfaces";

export const mockData: Auto[] = [
    {
        id: 1,
        id_customer: '123123',
        identification_customer: 'Cliente 1',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 2,
        id_customer: '123123',
        identification_customer: 'Cliente 2',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 3,
        id_customer: '123123', identification_customer: 'Cliente 3',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 4,
        id_customer: '123123', identification_customer: 'Cliente 4',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 5,
        id_customer: '123123', identification_customer: 'Cliente 5',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 6,
        id_customer: '123123', identification_customer: 'Cliente 6',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 7,
        id_customer: '123123', identification_customer: 'Cliente 7',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 8,
        id_customer: '123123',
        identification_customer: 'Cliente 8',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 9,
        id_customer: '123123',
        identification_customer: 'Cliente 9',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 10,
        id_customer: '123123',
        identification_customer: 'Cliente 10',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 11,
        id_customer: '123123',
        identification_customer: 'Cliente 11',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 12,
        id_customer: '123123',
        identification_customer: 'Cliente 12',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 13,
        id_customer: '123123',
        identification_customer: 'Cliente 13',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 14,
        id_customer: '123123',
        identification_customer: 'Cliente 14',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 15,
        id_customer: '123123',
        identification_customer: 'Cliente 15',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 16,
        id_customer: '123123',
        identification_customer: 'Cliente 16',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 17,
        id_customer: '123123',
        identification_customer: 'Cliente 17',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 18,
        id_customer: '123123',
        identification_customer: 'Cliente 18',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 19,
        id_customer: '123123',
        identification_customer: 'Cliente 19',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 20,
        id_customer: '123123',
        identification_customer: 'Cliente 20',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },
    {
        id: 21,
        id_customer: '123123',
        identification_customer: 'Cliente 21',
        car_model: '2023',
        factors: 'Recomendaciones',
        test_drive_qualification: 4,
        satisfaction_rating: 5,
    },

    // Agrega más autos según sea necesario
];

export const mockFactors: Factors[] = [
    { value: '', label: 'Seleccione una opción' },
    { value: 'Reputación de la Marca', label: 'Reputación de la Marca' },
    { value: 'Opciones de Financiamiento', label: 'Opciones de Financiamiento' },
    { value: 'Desempeño al Manejarlo', label: 'Desempeño al Manejarlo' },
    { value: 'Recomendaciones', label: 'Recomendaciones' },
    { value: 'Otros', label: 'Otros' },
]

export const initialFormCreate: IinitialFormCreate = {
    identificacion: '',
    modelo: '2023',
    factoresCompra: '',
    calificacionPrueba: 1,
    calificacionSatisfaccion: 1,
}

export const initialFormEdit: IinitialFormEdit = {
    identification_customer: '',
    car_model: '2023',
    factors: '',
    test_drive_qualification: 1,
    satisfaction_rating: 1,
}